### ISSUE TITLE
Integer <-> Optional cycle

### ISSUE THREAD

**Issue by glenfe** [boostorg/integer#16]
As of the following commit:
https://github.com/boostorg/integer/commit/fc4d6572019e3d61dd496b9f7a5423a4b1419eeb#r31545077
Integer depends on Optional depends on [Utility depends on Container_hash depends on] Integer.

**Comment by Lastique** [comment]
Any suggestions on how to fix this? I wouldn't want to revert the commit. I'm leaning towards to further decoupling Boost.Utility, though I'm not sure how effective that would be.

**Comment by NAThompson** [comment]
A very simple fix would be just to return a zero to indicate failure, rather than an optional.

**Comment by NAThompson** [comment]
Zero can indeed never be a valid result of the algorithm.

**Comment by Lastique** [comment]
Ok, would you prepare a PR, please?

**Comment by NAThompson** [comment]
I generally like to force people to do error handling using optional, but even I felt like this was a bit excessive for this particular case. That fact that it descends us into dependency hell made the case very clear.

**Comment by NAThompson** [comment]
Note that if the `boost::optional<Z>` gets into 1.69, then we've just made a backward incompatible change. Will the release manager allow us to put this into 1.69?

**Comment by glenfe** [comment]
The change that added the dependency on Optional is not in master so shouldn't be releasing with 1.69. So no compatibility will be broken.

**Comment by Lastique** [comment]
Resolved by https://github.com/boostorg/integer/pull/17.
