### ISSUE TITLE
travis error

### ISSUE THREAD

**Issue by sdarwin** [boostorg/integer#27]
One travis job is failing, I also get the same error in tests. 
Any ideas? https://travis-ci.org/github/boostorg/integer/jobs/756933421

```
...failed updating 3 targets...
...skipped 9 targets...
...updated 333 targets...
```

**Comment by Lastique** [comment]
The error is [caused](https://travis-ci.org/github/boostorg/integer/jobs/756933421#L810) by Boost.Multiprecision, please report it [there](https://github.com/boostorg/multiprecision/issues/new/choose).

**Comment by jzmaddock** [comment]
Hmmm... I suspect gcc-4.8 is going to be on the unsupported list for Multiprecision.  I realise it has pre-C++11 support but there are enough differences to make support not worthwhile at this point.  Though if there are enough complaints I might reconsider.

If you wanted to work around this here, then adding cxx11_type_traits to the requires clause for those tests would do the trick.  I think the thing to do is to add an alias target to multiprecision with the "official" usage requirements and then propagate it's use here.  I'll file a PR once the necessary target is in Multiprecision and the master project has cycled and updated.

**Comment by NAThompson** [comment]
Here's my vote for deprecating gcc 4.8.

**Comment by jzmaddock** [comment]
Apparently alias targets don't propagate <build>no, so I've filed the usual manual fix.

**Comment by Lastique** [comment]
@jzmaddock @NAThompson While you could deprecate gcc 4.8, the build log indicates genuine bugs, like mismatching `const` vs `constexpr`.

Also, Boost.Multiprecision use in Boost.Integer tests is conditioned on C++ compliance checks [here](https://github.com/boostorg/integer/blob/092d94c833a956054a240dd182001aaad2aac75e/test/multiprecision_config.hpp#L21), which were taken from Boost.Multiprecision sources. The fact that the tests with Boost.Multiprecision run on gcc 4.8 means the compiler is compliant. If you're planning to deprecate it then please specify which C++ feature it is missing so I can add it to the list of checks.

**Comment by Lastique** [comment]
> then please specify which C++ feature it is missing so I can add it to the list of checks.

Oh, I didn't see your PR, sorry.
